


kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "mlogistics.fullname" . }}-{{ .Values.loasfrontend.name }}-cm
  namespace: {{ .Release.Namespace | quote }}
data:
  nsswitch.conf: |
    # /etc/nsswitch.conf
    #
    # Example configuration of GNU Name Service Switch functionality.
    # If you have the `glibc-doc-reference' and `info' packages installed, try:
    # `info libc "Name Service Switch"' for information about this file.

    passwd:         files systemd
    group:          files systemd
    shadow:         files systemd
    gshadow:        files systemd

    hosts:          /mnt/hosts
    networks:       files

    protocols:      db files
    services:       db files
    ethers:         db files
    rpc:            db files

    netgroup:       nis