apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mlogistics.fullname" . }}-{{ .Values.loasfrontend.name }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "mlogistics.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "mlogistics.fullname" . }}-{{ .Values.loasfrontend.name }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.loasfrontend.replicas | default .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mlogistics.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        component: {{ .Values.loasfrontend.name }}
        {{- include "mlogistics.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mlogistics.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.loasfrontend.securityContext | nindent 8 }}
      initContainers:
        - name: init-hosts
          securityContext:
            runAsUser: 0  # Run as root to set permissions
            fsGroup: 0
          image: bitnami/kubectl
          command:
            - /bin/sh
            - -c
            - |
              HOSTS_FILE="/mnt/hosts"
              POD_NAME=$(hostname)
              POD_IP=$(hostname -i)

              # Ensure localhost exists
              if ! grep -q "127.0.0.1 localhost" "$HOSTS_FILE"; then
                echo "127.0.0.1 localhost" >> "$HOSTS_FILE"
              fi

              # Check if an entry for this pod already exists, and update or append
              if grep -q "$POD_NAME" "$HOSTS_FILE"; then
                # Replace existing entry for this pod
                sed -i "/$POD_NAME/d" "$HOSTS_FILE"
              fi
              # Add the current pod's IP and name to the hosts file
              echo "$POD_IP $POD_NAME" >> "$HOSTS_FILE"
          volumeMounts:
          - name: hosts
            mountPath: /mnt
      containers:
        - name: {{ .Chart.Name }}-{{ .Values.loasfrontend.name }}-main
          securityContext:
            {{- toYaml .Values.loasfrontend.securityContext | nindent 12 }}
          image: "{{ .Values.loasfrontend.image.name }}:{{ .Values.loasfrontend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.loasfrontend.image.pullPolicy }}
          ports:
          - containerPort: 8080
            protocol: TCP
          env:
          - name: HOSTALIASES
            value: /mnt/hosts
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: MY_POD_SERVICE_ACCOUNT
            valueFrom:
              fieldRef:
                fieldPath: spec.serviceAccountName
          resources:
            {{- toYaml .Values.loasfrontend.resources | nindent 12 }}
          volumeMounts:
          - name: shared
            mountPath: /home/mlog/shared
          - name: hosts
            mountPath: /mnt
          - name: logvol
            mountPath: /home/mlog/local/log
      volumes:
        - name: shared
          persistentVolumeClaim:
            claimName: mlogistics-shared
        - name: hosts
          persistentVolumeClaim:
            claimName: mlogistics-hosts   
        - name: logvol
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
