apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: pod-reader-binding
subjects:
  - kind: ServiceAccount
    name:  {{ include "mlogistics.serviceAccountName" . }}
    namespace: {{ .Release.Namespace | quote }}
roleRef:
  kind: Role
  name: pod-reader-role
  apiGroup: rbac.authorization.k8s.io