apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mlogistics.fullname" . }}-{{ .Values.lodelivery.name }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "mlogistics.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "mlogistics.fullname" . }}-{{ .Values.lodelivery.name }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mlogistics.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        component: {{ .Values.lodelivery.name }}
        {{- include "mlogistics.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      automountServiceAccountToken: false
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mlogistics.serviceAccountName" . }}
      securityContext:
       {{- toYaml .Values.lodelivery.securityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-{{ .Values.lodelivery.name }}-main
          securityContext:
            {{- toYaml .Values.lodelivery.securityContext | nindent 12 }}
          image: "{{ .Values.lodelivery.image.name }}:{{ .Values.lodelivery.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.lodelivery.image.pullPolicy }}
          env:
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: MY_POD_SERVICE_ACCOUNT
            valueFrom:
              fieldRef:
                fieldPath: spec.serviceAccountName
          resources:
            {{- toYaml .Values.lodelivery.resources | nindent 12 }}
          volumeMounts:
          - name: shared
            mountPath: /home/mlog/shared
      volumes:
        - name: shared
          persistentVolumeClaim:
            claimName: mlogistics-shared   
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
