{{- if .Values.loastimer.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mlogistics.fullname" . }}-{{ .Values.loastimer.name }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "mlogistics.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.loastimer.service.port }}
  selector:
    component: {{ .Values.loastimer.name }}
    {{- include "mlogistics.selectorLabels" . | nindent 4 }}
{{- end }}