apiVersion: v1
kind: Service
metadata:
  name: svc-loas-frontend-{{ .Values.service.suffix }}-dns
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "mlogistics.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 53
      protocol: UDP
      targetPort: 53
  selector:
    component: {{ .Values.loasfrontend.name }}-dns
    {{- include "mlogistics.selectorLabels" . | nindent 4 }}
