apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mlogistics.fullname" . }}-shared
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "mlogistics.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.persistence.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.persistence.capacity }}
