apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.registry.secretName }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "mlogistics.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.registry.credentials }}