apiVersion: v1
kind: Service
metadata:
  name: svc-lodoc-{{ .Values.service.suffix }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "mlogistics.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.lodoc.service.port }}
  selector:
    component: {{ .Values.lodoc.name }}
    {{- include "mlogistics.selectorLabels" . | nindent 4 }}
