apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mlogistics.fullname" . }}-{{ .Values.logserver.name }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "mlogistics.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "mlogistics.fullname" . }}-{{ .Values.logserver.name }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mlogistics.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        component: {{ .Values.logserver.name }}
        {{- include "mlogistics.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mlogistics.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: init-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 1050:1050 /home/mlog/shared && chmod 775 /home/mlog/shared"]
          securityContext:
            runAsUser: 0  # Run as root to set permissions
          volumeMounts:
          - name: shared
            mountPath: /home/mlog/shared
      containers:
        - name: {{ .Chart.Name }}-{{ .Values.logserver.name }}-main
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.logserver.main.image.name }}:{{ .Values.logserver.main.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.logserver.main.image.pullPolicy }}
          ports:
          - containerPort: 8010
            protocol: TCP
          env:
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: MY_POD_SERVICE_ACCOUNT
            valueFrom:
              fieldRef:
                fieldPath: spec.serviceAccountName
          resources:
            {{- toYaml .Values.logserver.resources | nindent 12 }}
          volumeMounts:
          - name: shared
            mountPath: /home/mlog/shared
          - name: logvol
            mountPath: /home/mlog/logs
        {{- if .Values.logserver.sidecar.enabled -}}
        - name: {{ .Chart.Name }}-{{ .Values.logserver.name }}-sidecar
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.logserver.sidecar.image.name }}:{{ .Values.logserver.sidecar.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.logserver.main.image.pullPolicy }}
          env:
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: MY_POD_SERVICE_ACCOUNT
            valueFrom:
              fieldRef:
                fieldPath: spec.serviceAccountName
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: shared
            mountPath: /home/mlog/shared
          - name: logvol
            mountPath: /home/mlog/logs
        {{- end }}
      volumes:
        - name: shared
          persistentVolumeClaim:
            claimName: mlogistics-shared
        - name: logvol
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
